import { v4 as uuidv4 } from 'uuid';

export const gamesData = [
  {
    id: uuidv4(),
    name: 'DOTA 2 High ranked MMR (18+)',
    logo: '/img/games-img/dota2card.jpg',
    rank: '/img/players-img/amateur.png',
    cardMap: '/img/games-img/dota2map.jpg',
    signPlayers: 0,
    maxPlayers: 10,
  },
  {
    id: uuidv4(),
    name: 'CS:GO World Cup I',
    logo: '/img/games-img/csgocard.jpg',
    rank: '/img/players-img/novice.png',
    cardMap: '/img/games-img/csgomap.png',
    signPlayers: 0,
    maxPlayers: 10,
  },
  {
    id: uuidv4(),
    name: 'WoT Last Fight Tournament',
    logo: '/img/games-img/wotcard.jpg',
    rank: '/img/players-img/expert.png',
    cardMap: '/img/games-img/wotmap.jpg',
    signPlayers: 0,
    maxPlayers: 30,
  },
  {
    id: uuidv4(),
    name: 'LOL 1x1 Fight (Fav Champs)',
    logo: '/img/games-img/lolcard.jpg',
    rank: '/img/players-img/novice.png',
    cardMap: '/img/games-img/lolmap.jpg',
    signPlayers: 0,
    maxPlayers: 10,
  },
  {
    id: uuidv4(),
    name: 'PUBG CIS Battle Royal (21+) ',
    logo: '/img/games-img/pubgcard.jpg',
    rank: '/img/players-img/expert.png',
    cardMap: '/img/games-img/pubgmap.jpg',
    signPlayers: 0,
    maxPlayers: 25,
  },
  {
    id: uuidv4(),
    name: 'FarCry 6 DeathMatch Tournament',
    logo: '/img/games-img/farcrycard.jpg',
    rank: '/img/players-img/expert.png',
    cardMap: '/img/games-img/farcry6map.jpg',
    signPlayers: 0,
    maxPlayers: 10,
  },
];
